// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type counterApp struct {
	count        *tui.State[int]
	incrementBtn *tui.Ref
	decrementBtn *tui.Ref
}

func Counter() *counterApp {
	return &counterApp{
		count:        tui.NewState(0),
		incrementBtn: tui.NewRef(),
		decrementBtn: tui.NewRef(),
	}
}

func (c *counterApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('+', func(ke tui.KeyEvent) { c.increment() }),
		tui.OnRune('-', func(ke tui.KeyEvent) { c.decrement() }),
	}
}

func (c *counterApp) HandleMouse(me tui.MouseEvent) bool {
	return tui.HandleClicks(me,
		tui.Click(c.incrementBtn, c.increment),
		tui.Click(c.decrementBtn, c.decrement),
	)
}

func (c *counterApp) increment() {
	c.count.Set(c.count.Get() + 1)
}

func (c *counterApp) decrement() {
	c.count.Set(c.count.Get() - 1)
}

func (c *counterApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("Reactive Counter"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithHR(),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Count:"),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(fmt.Sprintf("%d", c.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_1.AddChild(__tui_5)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_7 := tui.New()
	c.incrementBtn.Set(__tui_7)
	__tui_8 := tui.New(tui.WithText(" + "))
	__tui_7.AddChild(__tui_8)
	__tui_6.AddChild(__tui_7)
	__tui_9 := tui.New()
	c.decrementBtn.Set(__tui_9)
	__tui_10 := tui.New(tui.WithText(" - "))
	__tui_9.AddChild(__tui_10)
	__tui_6.AddChild(__tui_9)
	__tui_0.AddChild(__tui_6)
	__tui_11 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_12 := tui.New(
		tui.WithText("Press +/- or q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_12)
	__tui_0.AddChild(__tui_11)

	return __tui_0
}

func (c *counterApp) BindApp(app *tui.App) {
	if c.count != nil {
		c.count.BindApp(app)
	}
}

var _ tui.AppBinder = (*counterApp)(nil)
