// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type CounterUIView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v CounterUIView) GetRoot() tui.Renderable { return v.Root }

func (v CounterUIView) GetWatchers() []tui.Watcher { return v.watchers }

func CounterUI(count int) CounterUIView {
	var view CounterUIView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_2 := tui.New(
		tui.WithBackground(tui.NewStyle().Background(tui.Red)),
		tui.WithWidthPercent(100.00),
		tui.WithHeight(1),
	)
	__tui_3 := tui.New(
		tui.WithText("Counter Examples"),
		tui.WithTextAlign(tui.TextAlignCenter),
		tui.WithWidthPercent(100.00),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_2.AddChild(__tui_3)
	__tui_1.AddChild(__tui_2)
	__tui_4 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("Count:"),
	)
	__tui_1.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText(fmt.Sprintf("%d", count)),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_1.AddChild(__tui_6)
	__tui_0.AddChild(__tui_1)
	__tui_7 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_9 := tui.New(
		tui.WithText("Press +/- to change, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_8.AddChild(__tui_9)
	__tui_0.AddChild(__tui_8)

	view = CounterUIView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
