// Code generated by tui generate. DO NOT EDIT.
// Source: refs.tui

package main

import (
	"fmt"
	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func itemStyle(idx, selected int) string {
	if idx == selected {
		return "font-bold text-cyan"
	}
	return "text-white"
}

type RefsDemoView struct {
	Root      *element.Element
	Header    *element.Element
	Content   *element.Element
	Items     []*element.Element
	Warning   *element.Element // may be nil
	StatusBar *element.Element
}

func RefsDemo(items []string, showWarning bool, selectedIdx int) RefsDemoView {
	var view RefsDemoView

	var Items []*element.Element
	var Warning *element.Element

	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithHeight(24),
		element.WithWidth(80),
	)
	Header := element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithHeight(3),
		element.WithDirection(layout.Row),
		element.WithJustify(layout.JustifyCenter),
		element.WithAlign(layout.AlignCenter),
	)
	__tui_1 := element.New(
		element.WithText("Named Element Refs Demo"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	Header.AddChild(__tui_1)
	__tui_0.AddChild(Header)
	Content := element.New(
		element.WithDirection(layout.Column),
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithFlexGrow(1),
		element.WithScrollable(element.ScrollVertical),
		element.WithDirection(layout.Column),
	)
	__tui_2 := element.New(
		element.WithText("Items (loop refs) - j/k to scroll, +/- to select"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	Content.AddChild(__tui_2)
	for i, item := range items {
		_ = i
		__tui_3 := element.New(
			element.WithText(item),
		)
		Items = append(Items, __tui_3)
		Content.AddChild(__tui_3)
	}
	__tui_0.AddChild(Content)
	if showWarning {
		__tui_4 := element.New(
			element.WithBorder(tui.BorderDouble),
			element.WithPadding(1),
			element.WithHeight(3),
			element.WithDirection(layout.Row),
			element.WithJustify(layout.JustifyCenter),
			element.WithAlign(layout.AlignCenter),
			element.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		Warning = __tui_4
		__tui_5 := element.New(
			element.WithText("⚠ Warning: This is a conditional ref (may be nil)"),
			element.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_4.AddChild(__tui_5)
		__tui_0.AddChild(__tui_4)
	}
	StatusBar := element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithHeight(3),
		element.WithDirection(layout.Row),
		element.WithJustify(layout.JustifySpaceBetween),
		element.WithAlign(layout.AlignCenter),
	)
	__tui_6 := element.New(
		element.WithText("j/k: scroll | +/-: select | Tab: warning | d: switch demo | q: quit"),
		element.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	StatusBar.AddChild(__tui_6)
	__tui_7 := element.New(
		element.WithText(fmt.Sprintf("Selected: %d", selectedIdx)),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	StatusBar.AddChild(__tui_7)
	__tui_0.AddChild(StatusBar)

	view = RefsDemoView{
		Root:      __tui_0,
		Header:    Header,
		Content:   Content,
		Items:     Items,
		Warning:   Warning,
		StatusBar: StatusBar,
	}
	return view
}

type KeyedRefsDemoView struct {
	Root  *element.Element
	Users map[string]*element.Element
}

func KeyedRefsDemo(users []User) KeyedRefsDemoView {
	var view KeyedRefsDemoView

	Users := make(map[string]*element.Element)

	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithPadding(1),
		element.WithHeight(20),
		element.WithWidth(60),
	)
	__tui_1 := element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithHeight(3),
		element.WithDirection(layout.Row),
		element.WithJustify(layout.JustifyCenter),
		element.WithAlign(layout.AlignCenter),
	)
	__tui_2 := element.New(
		element.WithText("Keyed Refs Demo (map access)"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := element.New(
		element.WithDirection(layout.Column),
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithFlexGrow(1),
	)
	__tui_4 := element.New(
		element.WithText("Users (keyed by ID)"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_3.AddChild(__tui_4)
	for _, user := range users {
		__tui_5 := element.New(
			element.WithText(fmt.Sprintf("[%s] %s", user.ID, user.Name)),
		)
		Users[user.ID] = __tui_5
		__tui_3.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_3)
	__tui_6 := element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithHeight(2),
	)
	__tui_7 := element.New(
		element.WithText("1-3: highlight user | d: switch demo | q: quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_6.AddChild(__tui_7)
	__tui_0.AddChild(__tui_6)

	view = KeyedRefsDemoView{
		Root:  __tui_0,
		Users: Users,
	}
	return view
}
