// Code generated by tui generate. DO NOT EDIT.
// Source: simple.gsx

package example

import (
	tui "github.com/grindlemire/go-tui"
)

func Header(title string) *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
	)
	__tui_0.AddChild(__tui_1)
	return __tui_0
}

func Footer() *tui.Element {
	__tui_0 := tui.New(
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Footer content"),
	)
	__tui_0.AddChild(__tui_1)
	return __tui_0
}

func SimpleCard(title string, content string) *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(content),
	)
	__tui_0.AddChild(__tui_2)
	return __tui_0
}
