// Code generated by tui generate. DO NOT EDIT.
// Source: tree.gsx

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	tui "github.com/grindlemire/go-tui"
)

var _ = fmt.Sprintf

type Node struct {
	Name     string
	Children []Node
}

type visibleNode struct {
	node      Node
	depth     int
	path      string
	isDir     bool
	isLast    bool
	ancestors []bool
}

type directoryTree struct {
	rootPath        string
	tree            []Node
	cursor          *tui.State[int]
	expanded        *tui.State[map[string]bool]
	scrollY         *tui.State[int]
	scrollContainer *tui.Ref
}

func readDir(path string) []Node {
	entries, err := os.ReadDir(path)
	if err != nil {
		return nil
	}

	var children []Node
	for _, entry := range entries {
		// Skip hidden files/directories
		if entry.Name()[0] == '.' {
			continue
		}
		node := Node{Name: entry.Name()}
		if entry.IsDir() {
			node.Children = readDir(filepath.Join(path, entry.Name()))
			if node.Children == nil {
				// Empty directory: use a sentinel so it's still recognized as a dir
				node.Children = []Node{}
			}
		}
		children = append(children, node)
	}
	sortChildren(children)
	return children
}

func sortChildren(children []Node) {
	sort.Slice(children, func(i, j int) bool {
		iDir := children[i].Children != nil
		jDir := children[j].Children != nil
		if iDir != jDir {
			return iDir // directories first
		}
		return children[i].Name < children[j].Name
	})
}

func DirectoryTree(root string) *directoryTree {
	name := filepath.Base(root)
	rootNode := Node{
		Name:     name,
		Children: readDir(root),
	}
	if rootNode.Children == nil {
		rootNode.Children = []Node{}
	}
	tree := []Node{rootNode}
	return &directoryTree{
		rootPath:        root,
		cursor:          tui.NewState(0),
		expanded:        tui.NewState(map[string]bool{name: true}),
		scrollY:         tui.NewState(0),
		tree:            tree,
		scrollContainer: tui.NewRef(),
	}
}

func (d *directoryTree) navigateUp() {
	parent := filepath.Dir(d.rootPath)
	if parent == d.rootPath {
		return // already at filesystem root
	}
	d.rootPath = parent
	name := filepath.Base(parent)
	rootNode := Node{
		Name:     name,
		Children: readDir(parent),
	}
	if rootNode.Children == nil {
		rootNode.Children = []Node{}
	}
	d.tree = []Node{rootNode}
	d.cursor.Set(0)
	d.expanded.Set(map[string]bool{name: true})
	d.scrollY.Set(0)
}

func (d *directoryTree) selectedPath() string {
	visible := d.flatten()
	cur := d.cursor.Get()
	if cur >= len(visible) {
		return ""
	}
	return visible[cur].path
}

func (d *directoryTree) scrollToCursor() {
	el := d.scrollContainer.El()
	if el == nil {
		return
	}
	cur := d.cursor.Get()
	_, vpH := el.ViewportSize()
	y := d.scrollY.Get()
	if cur < y {
		d.scrollY.Set(cur)
	} else if cur >= y+vpH {
		d.scrollY.Set(cur - vpH + 1)
	}
}

func (d *directoryTree) flatten() []visibleNode {
	var result []visibleNode
	expanded := d.expanded.Get()
	for i, node := range d.tree {
		d.flattenNode(node, 0, node.Name, i == len(d.tree)-1, nil, expanded, &result)
	}
	return result
}

func (d *directoryTree) flattenNode(n Node, depth int, path string, isLast bool, ancestors []bool, expanded map[string]bool, result *[]visibleNode) {
	isDir := n.Children != nil
	*result = append(*result, visibleNode{
		node:      n,
		depth:     depth,
		path:      path,
		isDir:     isDir,
		isLast:    isLast,
		ancestors: ancestors,
	})
	if isDir && expanded[path] {
		newAncestors := make([]bool, len(ancestors)+1)
		copy(newAncestors, ancestors)
		newAncestors[len(ancestors)] = isLast
		for i, child := range n.Children {
			childPath := path + "/" + child.Name
			d.flattenNode(child, depth+1, childPath, i == len(n.Children)-1, newAncestors, expanded, result)
		}
	}
}

func buildPrefix(vn visibleNode) string {
	if vn.depth == 0 {
		return ""
	}
	prefix := ""
	for i := 0; i < vn.depth-1; i++ {
		if vn.ancestors[i+1] {
			prefix += "    "
		} else {
			prefix += "│   "
		}
	}
	if vn.isLast {
		prefix += "└── "
	} else {
		prefix += "├── "
	}
	return prefix
}

func nodeLabel(vn visibleNode, expanded map[string]bool) string {
	if vn.isDir {
		if expanded[vn.path] {
			return "▼ " + vn.node.Name
		}
		return "▶ " + vn.node.Name
	}
	return vn.node.Name
}

func isOnPath(vn visibleNode, selectedPath string) bool {
	if vn.path == selectedPath {
		return true
	}
	// Check if selectedPath starts with this node's path followed by "/"
	return len(selectedPath) > len(vn.path) && selectedPath[:len(vn.path)+1] == vn.path+"/"
}

func (d *directoryTree) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { d.moveUp() }),
		tui.OnRune('k', func(ke tui.KeyEvent) { d.moveUp() }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { d.moveDown() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { d.moveDown() }),
		tui.OnKey(tui.KeyEnter, func(ke tui.KeyEvent) { d.toggle() }),
		tui.OnKey(tui.KeyRight, func(ke tui.KeyEvent) { d.toggle() }),
		tui.OnRune('l', func(ke tui.KeyEvent) { d.toggle() }),
		tui.OnKey(tui.KeyLeft, func(ke tui.KeyEvent) { d.collapseOrParent() }),
		tui.OnRune('h', func(ke tui.KeyEvent) { d.collapseOrParent() }),
	}
}

func (d *directoryTree) moveUp() {
	d.cursor.Update(func(v int) int {
		if v > 0 {
			return v - 1
		}
		return v
	})
	d.scrollToCursor()
}

func (d *directoryTree) moveDown() {
	visible := d.flatten()
	d.cursor.Update(func(v int) int {
		if v < len(visible)-1 {
			return v + 1
		}
		return v
	})
	d.scrollToCursor()
}

func (d *directoryTree) toggle() {
	visible := d.flatten()
	cur := d.cursor.Get()
	if cur >= len(visible) {
		return
	}
	vn := visible[cur]
	if !vn.isDir {
		return
	}
	d.expanded.Update(func(m map[string]bool) map[string]bool {
		newMap := make(map[string]bool, len(m))
		for k, v := range m {
			newMap[k] = v
		}
		if newMap[vn.path] {
			delete(newMap, vn.path)
		} else {
			newMap[vn.path] = true
		}
		return newMap
	})
}

func (d *directoryTree) collapseOrParent() {
	visible := d.flatten()
	cur := d.cursor.Get()
	if cur >= len(visible) {
		return
	}
	vn := visible[cur]

	// If on an expanded directory, collapse it
	expanded := d.expanded.Get()
	if vn.isDir && expanded[vn.path] {
		d.expanded.Update(func(m map[string]bool) map[string]bool {
			newMap := make(map[string]bool, len(m))
			for k, v := range m {
				newMap[k] = v
			}
			delete(newMap, vn.path)
			return newMap
		})
		return
	}

	// Otherwise, jump to parent directory
	if vn.depth == 0 {
		d.navigateUp()
		return
	}
	// Find parent: walk backwards for a node at depth-1 that is a directory
	parentPath := vn.path[:len(vn.path)-len("/"+vn.node.Name)]
	for i := cur - 1; i >= 0; i-- {
		if visible[i].path == parentPath {
			d.cursor.Set(i)
			d.scrollToCursor()
			return
		}
	}
}

func (d *directoryTree) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
	)
	__tui_2 := tui.New(
		tui.WithText("Directory Tree"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(d.selectedPath()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollbarStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithScrollbarThumbStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
		tui.WithScrollOffset(0, d.scrollY.Get()),
	)
	d.scrollContainer.Set(__tui_5)
	for i, vn := range d.flatten() {
		_ = i
		if i == d.cursor.Get() {
			__tui_6 := tui.New(
				tui.WithText(buildPrefix(vn)+nodeLabel(vn, d.expanded.Get())),
				tui.WithBackground(tui.NewStyle().Background(tui.BrightBlack)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
			)
			__tui_5.AddChild(__tui_6)
		} else if isOnPath(vn, d.selectedPath()) {
			__tui_7 := tui.New(
				tui.WithText(buildPrefix(vn)+nodeLabel(vn, d.expanded.Get())),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_5.AddChild(__tui_7)
		} else if vn.isDir {
			__tui_8 := tui.New(
				tui.WithText(buildPrefix(vn)+nodeLabel(vn, d.expanded.Get())),
				tui.WithTextStyle(tui.NewStyle().Bold()),
			)
			__tui_5.AddChild(__tui_8)
		} else {
			__tui_9 := tui.New(
				tui.WithText(buildPrefix(vn) + nodeLabel(vn, d.expanded.Get())),
			)
			__tui_5.AddChild(__tui_9)
		}
	}
	__tui_0.AddChild(__tui_5)
	__tui_10 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithPadding(1),
	)
	__tui_12 := tui.New(
		tui.WithText("j/k: navigate | enter/l: expand | h: collapse | q: quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_12)
	__tui_0.AddChild(__tui_11)

	return __tui_0
}

func (d *directoryTree) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*directoryTree)
	if !ok {
		return
	}
	d.rootPath = f.rootPath
	d.tree = f.tree
}

var _ tui.PropsUpdater = (*directoryTree)(nil)

func (d *directoryTree) BindApp(app *tui.App) {
	if d.cursor != nil {
		d.cursor.BindApp(app)
	}
	if d.expanded != nil {
		d.expanded.BindApp(app)
	}
	if d.scrollY != nil {
		d.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*directoryTree)(nil)
