// Code generated by tui generate. DO NOT EDIT.
// Source: chat.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type InputBoxView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v InputBoxView) GetRoot() tui.Renderable { return v.Root }

func (v InputBoxView) GetWatchers() []tui.Watcher { return v.watchers }

func InputBox(text string, height int) InputBoxView {
	var view InputBoxView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithJustify(tui.JustifyEnd),
		tui.WithHeight(height),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_2 := tui.New(
		tui.WithText("> " + text + "\u2588"),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)

	view = InputBoxView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
