// Code generated by tui generate. DO NOT EDIT.
// Source: refs.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

func handleIncrement(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() + 1)
	}
}

func handleDecrement(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() - 1)
	}
}

type RefsView struct {
	Root         *tui.Element
	watchers     []tui.Watcher
	Counter      *tui.Element
	IncrementBtn *tui.Element
	DecrementBtn *tui.Element
	Status       *tui.Element
}

func (v RefsView) GetRoot() tui.Renderable { return v.Root }

func (v RefsView) GetWatchers() []tui.Watcher { return v.watchers }

func Refs() RefsView {
	var view RefsView
	var watchers []tui.Watcher

	var Counter *tui.Element
	var IncrementBtn *tui.Element
	var DecrementBtn *tui.Element
	var Status *tui.Element

	count := tui.NewState(0)
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithBorder(tui.BorderRounded),
	)
	__tui_1 := tui.New(
		tui.WithText("Named Element References"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	Counter = tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_3 := tui.New()
	__tui_4 := tui.New(tui.WithText("Counter"))
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(tui.WithText(fmt.Sprintf("%d", count.Get())))
	__tui_3.AddChild(__tui_5)
	Counter.AddChild(__tui_3)
	__tui_0.AddChild(Counter)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithWidthPercent(100.00),
		tui.WithJustify(tui.JustifyCenter),
	)
	IncrementBtn = tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithTextAlign(tui.TextAlignCenter),
		tui.WithPadding(1),
		tui.WithWidth(10),
		tui.WithHeight(5),
	)
	__tui_7 := tui.New(tui.WithText(" + "))
	IncrementBtn.AddChild(__tui_7)
	__tui_6.AddChild(IncrementBtn)
	DecrementBtn = tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithTextAlign(tui.TextAlignCenter),
		tui.WithPadding(1),
		tui.WithWidth(10),
		tui.WithHeight(5),
	)
	__tui_8 := tui.New(tui.WithText(" - "))
	DecrementBtn.AddChild(__tui_8)
	__tui_6.AddChild(DecrementBtn)
	__tui_0.AddChild(__tui_6)
	Status = tui.New(
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_9 := tui.New(
		tui.WithText("Click buttons to update the counter"),
	)
	Status.AddChild(__tui_9)
	__tui_0.AddChild(Status)
	__tui_10 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	// Attach handlers (deferred until refs are assigned)
	IncrementBtn.SetOnClick(handleIncrement(count))
	DecrementBtn.SetOnClick(handleDecrement(count))

	// State bindings
	count.Bind(func(_ int) {
		__tui_5.SetText(fmt.Sprintf("%d", count.Get()))
	})

	view = RefsView{
		Root:         __tui_0,
		watchers:     watchers,
		Counter:      Counter,
		IncrementBtn: IncrementBtn,
		DecrementBtn: DecrementBtn,
		Status:       Status,
	}
	return view
}
