// Code generated by tui generate. DO NOT EDIT.
// Source: dashboard.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

type dashboardApp struct {
	cardWidth  *tui.State[int]
	cardHeight *tui.State[int]
	growing    bool
}

var (
	_ tui.WatcherProvider = (*dashboardApp)(nil)
)

func Dashboard() *dashboardApp {
	return &dashboardApp{
		cardWidth:  tui.NewState(25),
		cardHeight: tui.NewState(6),
		growing:    true,
	}
}

func (d *dashboardApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
	}
}

func (d *dashboardApp) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnTimer(50*time.Millisecond, d.animate),
	}
}

func (d *dashboardApp) animate() {
	minW, maxW := 25, 50
	minH, maxH := 6, 12

	w := d.cardWidth.Get()
	if d.growing {
		w++
		if w >= maxW {
			d.growing = false
		}
	} else {
		w--
		if w <= minW {
			d.growing = true
		}
	}
	d.cardWidth.Set(w)
	d.cardHeight.Set(minH + (w-minW)*(maxH-minH)/(maxW-minW))
}

func cardSize(w, h int) string {
	return fmt.Sprintf("%dx%d", w, h)
}

func (d *dashboardApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
		tui.WithBorder(tui.BorderSingle),
		tui.WithHeight(3),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue)),
	)
	__tui_2 := tui.New(
		tui.WithText("Dashboard"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithFlexGrow(1),
	)
	__tui_4 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithBorder(tui.BorderSingle),
		tui.WithWidth(20),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_5 := tui.New(
		tui.WithText("Menu"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Magenta)),
	)
	__tui_4.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText("> Overview"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_4.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("  Settings"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_4.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("  Help"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_4.AddChild(__tui_8)
	__tui_3.AddChild(__tui_4)
	__tui_9 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_10 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
		tui.WithWidth(d.cardWidth.Get()),
		tui.WithHeight(d.cardHeight.Get()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_11 := tui.New(
		tui.WithText("Status Card"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText("Systems Online"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_10.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithText(cardSize(d.cardWidth.Get(), d.cardHeight.Get())),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_10.AddChild(__tui_13)
	__tui_9.AddChild(__tui_10)
	__tui_3.AddChild(__tui_9)
	__tui_0.AddChild(__tui_3)
	__tui_14 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithPadding(1),
		tui.WithFlexShrink(0),
	)
	__tui_15 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_14.AddChild(__tui_15)
	__tui_0.AddChild(__tui_14)

	return __tui_0
}

func (d *dashboardApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*dashboardApp)
	if !ok {
		return
	}
	d.growing = f.growing
}

var _ tui.PropsUpdater = (*dashboardApp)(nil)

func (d *dashboardApp) BindApp(app *tui.App) {
	if d.cardWidth != nil {
		d.cardWidth.BindApp(app)
	}
	if d.cardHeight != nil {
		d.cardHeight.BindApp(app)
	}
}

var _ tui.AppBinder = (*dashboardApp)(nil)
