// Code generated by tui generate. DO NOT EDIT.
// Source: composition.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type CardView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v CardView) GetRoot() tui.Renderable { return v.Root }

func (v CardView) GetWatchers() []tui.Watcher { return v.watchers }

func Card(title string, children []*tui.Element) CardView {
	var view CardView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	for _, __child := range children {
		__tui_0.AddChild(__child)
	}

	view = CardView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

type BadgeView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v BadgeView) GetRoot() tui.Renderable { return v.Root }

func (v BadgeView) GetWatchers() []tui.Watcher { return v.watchers }

func Badge(text string) BadgeView {
	var view BadgeView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithText(" "+text+" "),
		tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)

	view = BadgeView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

type HeaderView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v HeaderView) GetRoot() tui.Renderable { return v.Root }

func (v HeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func Header(text string) HeaderView {
	var view HeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderDouble),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText(text),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)

	view = HeaderView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

type AppView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v AppView) GetRoot() tui.Renderable { return v.Root }

func (v AppView) GetWatchers() []tui.Watcher { return v.watchers }

func App() AppView {
	var view AppView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(2),
		tui.WithPadding(2),
	)
	__tui_1 := Header("Component Composition Demo")
	__tui_0.AddChild(__tui_1.Root)
	__tui_3_children := []*tui.Element{}
	__tui_4 := tui.New(
		tui.WithText("Name: Alice"),
	)
	__tui_3_children = append(__tui_3_children, __tui_4)
	__tui_5 := tui.New(
		tui.WithText("Role: Admin"),
	)
	__tui_3_children = append(__tui_3_children, __tui_5)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_7 := tui.New(
		tui.WithText("Status:"),
	)
	__tui_6.AddChild(__tui_7)
	__tui_8 := Badge("Active")
	__tui_6.AddChild(__tui_8.Root)
	__tui_3_children = append(__tui_3_children, __tui_6)
	__tui_2 := Card("User Profile", __tui_3_children)
	__tui_0.AddChild(__tui_2.Root)
	__tui_10_children := []*tui.Element{}
	__tui_11 := tui.New(
		tui.WithText("Theme: Dark"),
	)
	__tui_10_children = append(__tui_10_children, __tui_11)
	__tui_12 := tui.New(
		tui.WithText("Notifications: On"),
	)
	__tui_10_children = append(__tui_10_children, __tui_12)
	__tui_13 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_14 := tui.New(
		tui.WithText("Version:"),
	)
	__tui_13.AddChild(__tui_14)
	__tui_15 := Badge("v1.0")
	__tui_13.AddChild(__tui_15.Root)
	__tui_10_children = append(__tui_10_children, __tui_13)
	__tui_9 := Card("Settings", __tui_10_children)
	__tui_0.AddChild(__tui_9.Root)
	__tui_16 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_16)

	watchers = append(watchers, __tui_1.GetWatchers()...)
	watchers = append(watchers, __tui_8.GetWatchers()...)
	watchers = append(watchers, __tui_2.GetWatchers()...)
	watchers = append(watchers, __tui_15.GetWatchers()...)
	watchers = append(watchers, __tui_9.GetWatchers()...)

	view = AppView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
