// Code generated by tui generate. DO NOT EDIT.
// Source: state.tui

package main

import (
	"fmt"
	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
	"time"
)

func increment(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() + 1)
	}
}

func decrement(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() - 1)
	}
}

func reset(count *tui.State[int]) func() {
	return func() {
		count.Set(0)
	}
}

func handleData(lines *tui.State[[]string]) func(string) {
	return func(line string) {
		lines.Set(append(lines.Get(), line))
	}
}

func handleKeys(v StreamingCounterView) func(tui.KeyEvent) {
	return func(e tui.KeyEvent) {
		switch e.Rune {
		case 'j':
			v.Content.ScrollBy(0, 1)
		case 'k':
			v.Content.ScrollBy(0, -1)
		case 'G':
			v.Content.ScrollToBottom()
		case 'g':
			v.Content.ScrollTo(0, 0)
		case 'q':
			tui.Stop()
		}
	}
}

func tick(elapsed *tui.State[int]) func() {
	return func() {
		elapsed.Set(elapsed.Get() + 1)
	}
}

type StreamingCounterView struct {
	Root     *element.Element
	watchers []tui.Watcher
	Content  *element.Element
}

func (v StreamingCounterView) GetRoot() tui.Renderable { return v.Root }

func (v StreamingCounterView) GetWatchers() []tui.Watcher { return v.watchers }

func StreamingCounter(dataCh chan string) StreamingCounterView {
	var view StreamingCounterView
	var watchers []tui.Watcher

	count := tui.NewState(0)
	lines := tui.NewState([]string{})
	elapsed := tui.NewState(0)
	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(1),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_1 := element.New(
		element.WithDirection(layout.Row),
		element.WithJustify(layout.JustifySpaceBetween),
	)
	__tui_2 := element.New(
		element.WithText("Streaming Counter"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := element.New(
		element.WithText(fmt.Sprintf("Count: %d | Time: %ds", count.Get(), elapsed.Get())),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(2),
	)
	__tui_5 := element.New(
		element.WithOnClick(increment(count)),
	)
	__tui_6 := element.New(element.WithText("+ Increment"))
	__tui_5.AddChild(__tui_6)
	__tui_4.AddChild(__tui_5)
	__tui_7 := element.New(
		element.WithOnClick(decrement(count)),
	)
	__tui_8 := element.New(element.WithText("- Decrement"))
	__tui_7.AddChild(__tui_8)
	__tui_4.AddChild(__tui_7)
	__tui_9 := element.New(
		element.WithOnClick(reset(count)),
	)
	__tui_10 := element.New(element.WithText("Reset"))
	__tui_9.AddChild(__tui_10)
	__tui_4.AddChild(__tui_9)
	__tui_0.AddChild(__tui_4)
	Content := element.New(
		element.WithDirection(layout.Column),
		element.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		element.WithScrollable(element.ScrollVertical),
		element.WithOnKeyPress(handleKeys(view)),
		element.WithFocusable(true),
		element.WithFlexGrow(1),
	)
	for _, line := range lines.Get() {
		__tui_11 := element.New(
			element.WithText(line),
		)
		Content.AddChild(__tui_11)
	}
	__tui_0.AddChild(Content)
	__tui_12 := element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithHeight(1),
	)
	__tui_13 := element.New(
		element.WithText(fmt.Sprintf("Lines: %d | j/k scroll, G bottom, g top, q quit", len(lines.Get()))),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_0.AddChild(__tui_12)

	watchers = append(watchers, tui.Watch(dataCh, handleData(lines)))
	watchers = append(watchers, tui.OnTimer(time.Second, tick(elapsed)))

	// State bindings
	__update___tui_3 := func() { __tui_3.SetText(fmt.Sprintf("Count: %d | Time: %ds", count.Get(), elapsed.Get())) }
	count.Bind(func(_ int) { __update___tui_3() })
	elapsed.Bind(func(_ int) { __update___tui_3() })
	lines.Bind(func(_ []string) {
		__tui_13.SetText(fmt.Sprintf("Lines: %d | j/k scroll, G bottom, g top, q quit", len(lines.Get())))
	})

	view = StreamingCounterView{
		Root:     __tui_0,
		watchers: watchers,
		Content:  Content,
	}
	return view
}
