// Code generated by tui generate. DO NOT EDIT.
// Source: header.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type HeaderView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v HeaderView) GetRoot() tui.Renderable { return v.Root }

func (v HeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func Header(state *AppState) HeaderView {
	var view HeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_1 := tui.New(
		tui.WithText("  AI Chat"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_3 := tui.New(
		tui.WithText(state.Model.Get()),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(fmt.Sprintf("%d tokens", state.TotalTokens.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_2.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("Ctrl+? help"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_5)
	__tui_0.AddChild(__tui_2)

	view = HeaderView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
