// Code generated by tui generate. DO NOT EDIT.
// Source: input_bar.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type inputBar struct {
	state  *AppState
	events *tui.Events[ChatEvent]
	text   *tui.State[string]
	active *tui.State[bool]
}

func InputBar(state *AppState, events *tui.Events[ChatEvent]) *inputBar {
	return &inputBar{
		state:  state,
		events: events,
		text:   tui.NewState(""),
		active: tui.NewState(true),
	}
}

func (i *inputBar) KeyMap() tui.KeyMap {
	if !i.active.Get() || i.state.IsStreaming.Get() {
		return nil
	}
	return tui.KeyMap{
		tui.OnRunesStop(i.appendChar),
		tui.OnKeyStop(tui.KeyBackspace, i.deleteChar),
		tui.OnKeyStop(tui.KeyEnter, i.submit),
	}
}

func (i *inputBar) appendChar(ke tui.KeyEvent) {
	i.text.Set(i.text.Get() + string(ke.Rune))
}

func (i *inputBar) deleteChar(ke tui.KeyEvent) {
	t := i.text.Get()
	if len(t) > 0 {
		// Handle UTF-8 properly
		runes := []rune(t)
		i.text.Set(string(runes[:len(runes)-1]))
	}
}

func (i *inputBar) submit(ke tui.KeyEvent) {
	t := i.text.Get()
	if t == "" {
		return
	}
	i.events.Emit(ChatEvent{Type: "submit", Payload: t})
	i.text.Set("")
}

func (i *inputBar) border() tui.BorderStyle {
	return tui.BorderRounded
}

func (i *inputBar) borderStyle() tui.Style {
	if i.state.IsStreaming.Get() {
		return tui.NewStyle().Foreground(tui.Yellow)
	}
	return tui.NewStyle().Foreground(tui.Cyan)
}

func (i *inputBar) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(i.border()),
		tui.WithBorderStyle(i.borderStyle()),
		tui.WithHeight(3),
		tui.WithPadding(1),
		tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
	)
	if i.state.IsStreaming.Get() {
		__tui_1 := tui.New(
			tui.WithText("  Generating..."),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Dim()),
		)
		__tui_0.AddChild(__tui_1)
	} else {
		__tui_2 := tui.New(
			tui.WithText("  "),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_0.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(i.text.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
		)
		__tui_0.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText(""),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_0.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithFlexGrow(1),
		)
		__tui_0.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText("  Enter to send"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_6)
	}

	return __tui_0
}
