// Code generated by tui generate. DO NOT EDIT.
// Source: markdown.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type viewer struct {
	doc     string
	scrollY *tui.State[int]
	content *tui.Ref
}

func Viewer() *viewer {
	return &viewer{
		doc:     sampleDoc,
		scrollY: tui.NewState(0),
		content: tui.NewRef(),
	}
}

func (v *viewer) scrollBy(delta int) {
	el := v.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := v.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	}
	if newY > maxY {
		newY = maxY
	}
	v.scrollY.Set(newY)
}

func (v *viewer) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('j'), func(ke tui.KeyEvent) { v.scrollBy(1) }),
		tui.On(tui.Rune('k'), func(ke tui.KeyEvent) { v.scrollBy(-1) }),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) { v.scrollBy(1) }),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) { v.scrollBy(-1) }),
		tui.On(tui.KeyPageDown, func(ke tui.KeyEvent) { v.scrollBy(10) }),
		tui.On(tui.KeyPageUp, func(ke tui.KeyEvent) { v.scrollBy(-10) }),
	}
}

func (v *viewer) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		v.scrollBy(-3)
		return true
	case tui.MouseWheelDown:
		v.scrollBy(3)
		return true
	}
	return false
}

func (v *viewer) mdWidth(app *tui.App) int {
	w, _ := app.Size()
	if w < 10 {
		w = 10
	}
	return w
}

func (v *viewer) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
	)
	__tui_1 := tui.New(
		tui.WithText("Markdown Viewer"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollbarHidden(true),
		tui.WithFlexGrow(1),
		tui.WithScrollOffset(0, v.scrollY.Get()),
	)
	v.content.Set(__tui_2)
	__tui_3 := app.MountPersistent(v, 0, func() tui.Component {
		return tui.NewMarkdown(
			tui.WithMarkdownSource(v.doc),
			tui.WithMarkdownWidth(v.mdWidth(app)),
		)
	})
	__tui_2.AddChild(__tui_3)
	__tui_0.AddChild(__tui_2)
	__tui_4 := tui.New(
		tui.WithText("scroll: wheel/j/k/arrows | select and click links natively | q/esc quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_4)

	return __tui_0
}

func (v *viewer) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*viewer)
	if !ok {
		return
	}
	v.doc = f.doc
}

var _ tui.PropsUpdater = (*viewer)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (v *viewer) bindAppFields(app *tui.App) {
	if v.scrollY != nil {
		v.scrollY.BindApp(app)
	}
}

func (v *viewer) BindApp(app *tui.App) {
	v.bindAppFields(app)
}

var _ tui.AppBinder = (*viewer)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener   = (*viewer)(nil)
	_ tui.MouseListener = (*viewer)(nil)
)
