// Code generated by tui generate. DO NOT EDIT.
// Source: streaming.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

func tick(elapsed *tui.State[int]) func() {
	return func() {
		elapsed.Set(elapsed.Get() + 1)
	}
}

func addLine(lineCount *tui.State[int], content *tui.Element) func(string) {
	return func(line string) {
		lineCount.Set(lineCount.Get() + 1)

		stayAtBottom := content.IsAtBottom()

		lineElem := tui.New(
			tui.WithText(line),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		content.AddChild(lineElem)

		if stayAtBottom {
			content.ScrollToBottom()
		}
	}
}

func handleScrollKeys(content *tui.Element) func(tui.KeyEvent) {
	return func(e tui.KeyEvent) {
		switch e.Rune {
		case 'j':
			content.ScrollBy(0, 1)
		case 'k':
			content.ScrollBy(0, -1)
		}
	}
}

type StreamingView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	Content  *tui.Element
}

func (v StreamingView) GetRoot() tui.Renderable { return v.Root }

func (v StreamingView) GetWatchers() []tui.Watcher { return v.watchers }

func Streaming(dataCh <-chan string) StreamingView {
	var view StreamingView
	var watchers []tui.Watcher

	var Content *tui.Element

	lineCount := tui.NewState(0)
	elapsed := tui.NewState(0)
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Streaming with Channels and Timers"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	Content = tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithFocusable(true),
	)
	__tui_0.AddChild(Content)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_4 := tui.New()
	__tui_5 := tui.New(tui.WithText("Lines:"))
	__tui_4.AddChild(__tui_5)
	__tui_6 := tui.New(tui.WithText(fmt.Sprintf("%d", lineCount.Get())))
	__tui_4.AddChild(__tui_6)
	__tui_3.AddChild(__tui_4)
	__tui_7 := tui.New()
	__tui_8 := tui.New(tui.WithText("Elapsed:"))
	__tui_7.AddChild(__tui_8)
	__tui_9 := tui.New(tui.WithText(fmt.Sprintf("%ds", elapsed.Get())))
	__tui_7.AddChild(__tui_9)
	__tui_3.AddChild(__tui_7)
	__tui_0.AddChild(__tui_3)
	__tui_10 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	// Attach handlers (deferred until refs are assigned)
	Content.SetOnKeyPress(handleScrollKeys(Content))

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, tick(elapsed)))
	__tui_0.AddWatcher(tui.Watch(dataCh, addLine(lineCount, Content)))

	// State bindings
	lineCount.Bind(func(_ int) {
		__tui_6.SetText(fmt.Sprintf("%d", lineCount.Get()))
	})
	elapsed.Bind(func(_ int) {
		__tui_9.SetText(fmt.Sprintf("%ds", elapsed.Get()))
	})

	view = StreamingView{
		Root:     __tui_0,
		watchers: watchers,
		Content:  Content,
	}
	return view
}
