// Code generated by tui generate. DO NOT EDIT.
// Source: settings.gsx

package settings

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

const (
	numSections = 4
	minTemp     = 0.0
	maxTemp     = 1.0
)

type settingsApp struct {
	state     *SettingsState
	saveBtn   *tui.Ref
	cancelBtn *tui.Ref
}

func SettingsApp(state *SettingsState) *settingsApp {
	return &settingsApp{
		state:     state,
		saveBtn:   tui.NewRef(),
		cancelBtn: tui.NewRef(),
	}
}

func (s *settingsApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEnter, func(ke tui.KeyEvent) { s.save() }),
		tui.OnKey(tui.KeyTab, func(ke tui.KeyEvent) { s.nextSection() }),
		tui.OnKeyStop(tui.KeyLeft, func(ke tui.KeyEvent) { s.handleLeft() }),
		tui.OnKeyStop(tui.KeyRight, func(ke tui.KeyEvent) { s.handleRight() }),
		tui.OnRune('h', func(ke tui.KeyEvent) { s.handleLeft() }),
		tui.OnRune('l', func(ke tui.KeyEvent) { s.handleRight() }),
	}
}

func (s *settingsApp) HandleMouse(me tui.MouseEvent) bool {
	return tui.HandleClicks(me,
		tui.Click(s.saveBtn, s.save),
		tui.Click(s.cancelBtn, func() { tui.Stop() }),
	)
}

func (s *settingsApp) save() {
	s.state.Saved.Set(true)
	tui.Stop()
}

func (s *settingsApp) nextSection() {
	next := s.state.FocusedSection.Get() + 1
	if next >= numSections {
		next = 0
	}
	s.state.FocusedSection.Set(next)
}

func (s *settingsApp) handleLeft() {
	section := s.state.FocusedSection.Get()
	switch section {
	case 0: // Provider
		s.cycleProvider(-1)
	case 1: // Model
		s.cycleModel(-1)
	case 2: // Temperature
		s.adjustTemp(-0.1)
	case 3:
		// System Prompt section: no action on left/right
	}
}

func (s *settingsApp) handleRight() {
	section := s.state.FocusedSection.Get()
	switch section {
	case 0:
		s.cycleProvider(1)
	case 1:
		s.cycleModel(1)
	case 2:
		s.adjustTemp(0.1)
	case 3:
		// System Prompt section: no action on left/right
	}
}

func (s *settingsApp) cycleProvider(dir int) {
	providers := s.state.AvailableProviders
	if len(providers) == 0 {
		return
	}
	current := s.state.Provider.Get()
	idx := 0
	for i, p := range providers {
		if p == current {
			idx = i
			break
		}
	}
	idx = idx + dir + len(providers)
	idx = wrapIndex(idx, len(providers))
	s.state.Provider.Set(providers[idx])
	// Update model to first of new provider
	models := s.state.ProviderModels[providers[idx]]
	if len(models) > 0 {
		s.state.Model.Set(models[0])
	}
}

func (s *settingsApp) cycleModel(dir int) {
	provider := s.state.Provider.Get()
	models := s.state.ProviderModels[provider]
	if len(models) == 0 {
		return
	}
	current := s.state.Model.Get()
	idx := 0
	for i, m := range models {
		if m == current {
			idx = i
			break
		}
	}
	idx = idx + dir + len(models)
	idx = wrapIndex(idx, len(models))
	s.state.Model.Set(models[idx])
}

func (s *settingsApp) adjustTemp(delta float64) {
	t := s.state.Temperature.Get() + delta
	if t < minTemp {
		t = minTemp
	} else if t > maxTemp {
		t = maxTemp
	}
	s.state.Temperature.Set(t)
}

func (s *settingsApp) borderStyleForSection(section int) tui.Style {
	if s.state.FocusedSection.Get() == section {
		return tui.NewStyle().Foreground(tui.Cyan)
	}
	return tui.NewStyle()
}

func wrapIndex(idx, length int) int {
	for idx < 0 {
		idx += length
	}
	for idx >= length {
		idx -= length
	}
	return idx
}

func (s *settingsApp) tempBar() string {
	t := s.state.Temperature.Get()
	pos := int(t * 29) // position 0-29 for 30 character bar
	bar := ""
	for i := 0; i < 30; i++ {
		if i < pos {
			bar += "━"
		} else if i == pos {
			bar += "●"
		} else {
			bar += "━"
		}
	}
	return bar
}

func (s *settingsApp) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithPadding(2),
		tui.WithGap(2),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("  Settings"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(s.borderStyleForSection(0)),
		tui.WithPadding(1),
	)
	__tui_4 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_5 := tui.New(
		tui.WithText("Provider"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_4.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	for _, p := range s.state.AvailableProviders {
		if p == s.state.Provider.Get() {
			__tui_7 := tui.New(
				tui.WithText("● "+p),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_6.AddChild(__tui_7)
		} else {
			__tui_8 := tui.New(
				tui.WithText("○ "+p),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_6.AddChild(__tui_8)
		}
	}
	__tui_4.AddChild(__tui_6)
	__tui_3.AddChild(__tui_4)
	__tui_0.AddChild(__tui_3)
	__tui_9 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(s.borderStyleForSection(1)),
		tui.WithPadding(1),
	)
	__tui_10 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_11 := tui.New(
		tui.WithText("Model"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	for _, m := range s.state.ProviderModels[s.state.Provider.Get()] {
		if m == s.state.Model.Get() {
			__tui_13 := tui.New(
				tui.WithText("● "+m),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_12.AddChild(__tui_13)
		} else {
			__tui_14 := tui.New(
				tui.WithText("○ "+m),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_12.AddChild(__tui_14)
		}
	}
	__tui_10.AddChild(__tui_12)
	__tui_9.AddChild(__tui_10)
	__tui_0.AddChild(__tui_9)
	__tui_15 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(s.borderStyleForSection(2)),
		tui.WithPadding(1),
	)
	__tui_16 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_17 := tui.New(
		tui.WithText("Temperature"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_16.AddChild(__tui_17)
	__tui_18 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_19 := tui.New(
		tui.WithText(s.tempBar()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_18.AddChild(__tui_19)
	__tui_20 := tui.New(
		tui.WithText(fmt.Sprintf("%.1f", s.state.Temperature.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_18.AddChild(__tui_20)
	__tui_16.AddChild(__tui_18)
	__tui_21 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_22 := tui.New(
		tui.WithText("← precise"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_21.AddChild(__tui_22)
	__tui_23 := tui.New(
		tui.WithText("creative →"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_21.AddChild(__tui_23)
	__tui_16.AddChild(__tui_21)
	__tui_15.AddChild(__tui_16)
	__tui_0.AddChild(__tui_15)
	__tui_24 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(s.borderStyleForSection(3)),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_25 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_26 := tui.New(
		tui.WithText("System Prompt"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_25.AddChild(__tui_26)
	__tui_27 := tui.New(
		tui.WithText(s.state.SystemPrompt.Get()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_25.AddChild(__tui_27)
	__tui_24.AddChild(__tui_25)
	__tui_0.AddChild(__tui_24)
	__tui_28 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithGap(2),
	)
	__tui_29 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithPadding(1),
	)
	s.saveBtn.Set(__tui_29)
	__tui_30 := tui.New(tui.WithText("  Save  "))
	__tui_29.AddChild(__tui_30)
	__tui_28.AddChild(__tui_29)
	__tui_31 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	s.cancelBtn.Set(__tui_31)
	__tui_32 := tui.New(tui.WithText("  Cancel  "))
	__tui_31.AddChild(__tui_32)
	__tui_28.AddChild(__tui_31)
	__tui_0.AddChild(__tui_28)
	__tui_33 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_34 := tui.New(
		tui.WithText("Tab: navigate  ←/→: select  Enter: save  Esc: cancel"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_33.AddChild(__tui_34)
	__tui_0.AddChild(__tui_33)

	return __tui_0
}
