// Code generated by tui generate. DO NOT EDIT.
// Source: components.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type componentsApp struct {
	scrollY *tui.State[int]
	content *tui.Ref
}

func App() *componentsApp {
	return &componentsApp{
		scrollY: tui.NewState(0),
		content: tui.NewRef(),
	}
}

func (a *componentsApp) scrollBy(delta int) {
	el := a.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := a.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	a.scrollY.Set(newY)
}

func (a *componentsApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { a.scrollBy(1) }),
		tui.OnRune('k', func(ke tui.KeyEvent) { a.scrollBy(-1) }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { a.scrollBy(1) }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { a.scrollBy(-1) }),
	}
}

func (a *componentsApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		a.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		a.scrollBy(1)
		return true
	}
	return false
}

func statusLabel(online bool) string {
	if online {
		return "Online"
	}
	return "Offline"
}

func statusColor(online bool) string {
	if online {
		return "text-green"
	}
	return "font-dim"
}

func (a *componentsApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(2),
		tui.WithGap(2),
	)
	__tui_1 := app.Mount(a, 0, func() tui.Component {
		return Header("Component Showcase")
	})
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_3 := app.Mount(a, 1, func() tui.Component {
		return UserCard("Alice", "Engineer", true)
	})
	__tui_2.AddChild(__tui_3)
	__tui_4 := app.Mount(a, 2, func() tui.Component {
		return UserCard("Bob", "Designer", false)
	})
	__tui_2.AddChild(__tui_4)
	__tui_5 := app.Mount(a, 3, func() tui.Component {
		return UserCard("Carol", "Manager", true)
	})
	__tui_2.AddChild(__tui_5)
	__tui_0.AddChild(__tui_2)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_7_children := []*tui.Element{}
	__tui_8 := app.Mount(a, 5, func() tui.Component {
		return StatusLine("Version:", "1.2.0")
	})
	__tui_7_children = append(__tui_7_children, __tui_8)
	__tui_9 := app.Mount(a, 6, func() tui.Component {
		return StatusLine("Uptime:", "3d 14h")
	})
	__tui_7_children = append(__tui_7_children, __tui_9)
	__tui_10 := app.Mount(a, 7, func() tui.Component {
		return StatusLine("Memory:", "1.2 GB")
	})
	__tui_7_children = append(__tui_7_children, __tui_10)
	__tui_7 := app.Mount(a, 4, func() tui.Component {
		return Card("System Info", __tui_7_children)
	})
	__tui_6.AddChild(__tui_7)
	__tui_11_children := []*tui.Element{}
	__tui_12 := app.Mount(a, 9, func() tui.Component {
		return StatusLine("Theme:", "Dark")
	})
	__tui_11_children = append(__tui_11_children, __tui_12)
	__tui_13 := app.Mount(a, 10, func() tui.Component {
		return StatusLine("Notify:", "On")
	})
	__tui_11_children = append(__tui_11_children, __tui_13)
	__tui_14 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_15 := tui.New(
		tui.WithText("Tags:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_14.AddChild(__tui_15)
	__tui_16 := app.Mount(a, 11, func() tui.Component {
		return Badge("New", "text-green")
	})
	__tui_14.AddChild(__tui_16)
	__tui_17 := app.Mount(a, 12, func() tui.Component {
		return Badge("v1.0", "text-cyan")
	})
	__tui_14.AddChild(__tui_17)
	__tui_11_children = append(__tui_11_children, __tui_14)
	__tui_11 := app.Mount(a, 8, func() tui.Component {
		return Card("Configuration", __tui_11_children)
	})
	__tui_6.AddChild(__tui_11)
	__tui_0.AddChild(__tui_6)
	__tui_18 := app.Mount(a, 13, func() tui.Component {
		return StatusBar()
	})
	__tui_0.AddChild(__tui_18)
	__tui_19 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_20 := tui.New(
		tui.WithText("j/k scroll|q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_19.AddChild(__tui_20)
	__tui_0.AddChild(__tui_19)

	return __tui_0
}

func (a *componentsApp) BindApp(app *tui.App) {
	if a.scrollY != nil {
		a.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*componentsApp)(nil)

type CardView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v CardView) GetRoot() tui.Renderable { return v.Root }

func (v CardView) GetWatchers() []tui.Watcher { return v.watchers }

func (v CardView) Render(app *tui.App) *tui.Element { return v.Root }

func (v CardView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = CardView{}

func Card(title string, children []*tui.Element) CardView {
	var view CardView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithWidthPercent(100.00),
		tui.WithFlexGrow(1.0),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	for _, __child := range children {
		__tui_3.AddChild(__child)
	}
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	view = CardView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

type BadgeView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v BadgeView) GetRoot() tui.Renderable { return v.Root }

func (v BadgeView) GetWatchers() []tui.Watcher { return v.watchers }

func (v BadgeView) Render(app *tui.App) *tui.Element { return v.Root }

func (v BadgeView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = BadgeView{}

func Badge(label string, color string) BadgeView {
	var view BadgeView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithText(label),
	)

	__bindApp := func(app *tui.App) {
	}

	view = BadgeView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

type HeaderView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v HeaderView) GetRoot() tui.Renderable { return v.Root }

func (v HeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func (v HeaderView) Render(app *tui.App) *tui.Element { return v.Root }

func (v HeaderView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = HeaderView{}

func Header(title string) HeaderView {
	var view HeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)

	__bindApp := func(app *tui.App) {
	}

	view = HeaderView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

type StatusLineView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v StatusLineView) GetRoot() tui.Renderable { return v.Root }

func (v StatusLineView) GetWatchers() []tui.Watcher { return v.watchers }

func (v StatusLineView) Render(app *tui.App) *tui.Element { return v.Root }

func (v StatusLineView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = StatusLineView{}

func StatusLine(label string, value string) StatusLineView {
	var view StatusLineView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText(label),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(value),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	view = StatusLineView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

type UserCardView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v UserCardView) GetRoot() tui.Renderable { return v.Root }

func (v UserCardView) GetWatchers() []tui.Watcher { return v.watchers }

func (v UserCardView) Render(app *tui.App) *tui.Element { return v.Root }

func (v UserCardView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = UserCardView{}

func UserCard(name string, role string, online bool) UserCardView {
	var view UserCardView
	var watchers []tui.Watcher

	__tui_1_children := []*tui.Element{}
	__tui_2 := tui.New(
		tui.WithText(role),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1_children = append(__tui_1_children, __tui_2)
	__tui_3 := Badge(statusLabel(online), statusColor(online))
	__tui_1_children = append(__tui_1_children, __tui_3.Root)
	__tui_0 := Card(name, __tui_1_children)

	watchers = append(watchers, __tui_3.GetWatchers()...)
	watchers = append(watchers, __tui_0.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := interface{}(__tui_3).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
		if binder, ok := interface{}(__tui_0).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	view = UserCardView{
		Root:     __tui_0.Root,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

type StatusBarView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v StatusBarView) GetRoot() tui.Renderable { return v.Root }

func (v StatusBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v StatusBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v StatusBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = StatusBarView{}

func StatusBar() StatusBarView {
	var view StatusBarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_1 := Badge("Build passed", "text-green")
	__tui_0.AddChild(__tui_1.Root)
	__tui_2 := tui.New(
		tui.WithText("|"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := Badge("3 warnings", "text-yellow")
	__tui_0.AddChild(__tui_3.Root)
	__tui_4 := tui.New(
		tui.WithText("|"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := Badge("v1.2.0", "text-cyan")
	__tui_0.AddChild(__tui_5.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)
	watchers = append(watchers, __tui_3.GetWatchers()...)
	watchers = append(watchers, __tui_5.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := interface{}(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
		if binder, ok := interface{}(__tui_3).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
		if binder, ok := interface{}(__tui_5).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	view = StatusBarView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}
