// Code generated by tui generate. DO NOT EDIT.
// Source: layout.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type LayoutView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v LayoutView) GetRoot() tui.Renderable { return v.Root }

func (v LayoutView) GetWatchers() []tui.Watcher { return v.watchers }

func Layout() LayoutView {
	var view LayoutView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Flexbox Layout Demo"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_4 := tui.New(
		tui.WithText("Row layout(flex):"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_6 := tui.New(
		tui.WithText("One"),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_5.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("Two"),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_5.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("Three"),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_5.AddChild(__tui_8)
	__tui_3.AddChild(__tui_5)
	__tui_0.AddChild(__tui_3)
	__tui_9 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_10 := tui.New(
		tui.WithText("Column layout(flex-col):"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_9.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_12 := tui.New(
		tui.WithText("First"),
		tui.WithPadding(1),
	)
	__tui_11.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithText("Second"),
		tui.WithPadding(1),
	)
	__tui_11.AddChild(__tui_13)
	__tui_14 := tui.New(
		tui.WithText("Third"),
		tui.WithPadding(1),
	)
	__tui_11.AddChild(__tui_14)
	__tui_9.AddChild(__tui_11)
	__tui_0.AddChild(__tui_9)
	__tui_15 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_16 := tui.New(
		tui.WithText("Justify content:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_15.AddChild(__tui_16)
	__tui_17 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_18 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyStart),
		tui.WithBorder(tui.BorderSingle),
		tui.WithWidth(20),
	)
	__tui_19 := tui.New(
		tui.WithText("start"),
	)
	__tui_18.AddChild(__tui_19)
	__tui_17.AddChild(__tui_18)
	__tui_20 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithBorder(tui.BorderSingle),
		tui.WithWidth(20),
	)
	__tui_21 := tui.New(
		tui.WithText("center"),
	)
	__tui_20.AddChild(__tui_21)
	__tui_17.AddChild(__tui_20)
	__tui_22 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyEnd),
		tui.WithBorder(tui.BorderSingle),
		tui.WithWidth(20),
	)
	__tui_23 := tui.New(
		tui.WithText("end"),
	)
	__tui_22.AddChild(__tui_23)
	__tui_17.AddChild(__tui_22)
	__tui_15.AddChild(__tui_17)
	__tui_0.AddChild(__tui_15)
	__tui_24 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_25 := tui.New(
		tui.WithText("Flex grow:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_24.AddChild(__tui_25)
	__tui_26 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithWidth(60),
	)
	__tui_27 := tui.New(
		tui.WithText("Fixed"),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_26.AddChild(__tui_27)
	__tui_28 := tui.New(
		tui.WithText("Grows to fill space"),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_26.AddChild(__tui_28)
	__tui_29 := tui.New(
		tui.WithText("Fixed"),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_26.AddChild(__tui_29)
	__tui_24.AddChild(__tui_26)
	__tui_0.AddChild(__tui_24)
	__tui_30 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_30)

	view = LayoutView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
