// Code generated by tui generate. DO NOT EDIT.
// Source: loops.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type loopsApp struct {
	items    []string
	selected *tui.State[int]
}

func Loops(items []string) *loopsApp {
	return &loopsApp{
		items:    items,
		selected: tui.NewState(0),
	}
}

func (l *loopsApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { l.next() }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { l.next() }),
		tui.OnRune('k', func(ke tui.KeyEvent) { l.prev() }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { l.prev() }),
	}
}

func (l *loopsApp) next() {
	itemCount := len(l.items)
	if itemCount == 0 {
		return
	}
	l.selected.Update(func(current int) int {
		if current < 0 || current >= itemCount-1 {
			return 0
		}
		return current + 1
	})
}

func (l *loopsApp) prev() {
	itemCount := len(l.items)
	if itemCount == 0 {
		return
	}
	l.selected.Update(func(current int) int {
		if current <= 0 || current >= itemCount {
			return itemCount - 1
		}
		return current - 1
	})
}

func (l *loopsApp) selectedIndex() int {
	itemCount := len(l.items)
	if itemCount == 0 {
		return -1
	}
	index := l.selected.Get()
	if index < 0 {
		return 0
	}
	if index >= itemCount {
		return itemCount - 1
	}
	return index
}

func (l *loopsApp) selectedItem() string {
	index := l.selectedIndex()
	if index < 0 {
		return ""
	}
	return l.items[index]
}

func (l *loopsApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Loop Rendering"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(fmt.Sprintf("Item %d/%d", l.selectedIndex()+1, len(l.items))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_5 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1.0),
	)
	__tui_6 := tui.New(
		tui.WithText("Simple @for"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_5.AddChild(__tui_6)
	for i, item := range l.items {
		_ = i
		if i == l.selectedIndex() {
			__tui_7 := tui.New(
				tui.WithText(item),
				tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
				tui.WithTextStyle(tui.NewStyle().Bold()),
			)
			__tui_5.AddChild(__tui_7)
		} else {
			__tui_8 := tui.New(
				tui.WithText(item),
			)
			__tui_5.AddChild(__tui_8)
		}
	}
	__tui_4.AddChild(__tui_5)
	__tui_9 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1.0),
	)
	__tui_10 := tui.New(
		tui.WithText("@for with index"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_9.AddChild(__tui_10)
	for i, item := range l.items {
		_ = i
		if i == l.selectedIndex() {
			__tui_11 := tui.New(
				tui.WithText(fmt.Sprintf("%d. %s", i+1, item)),
				tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
				tui.WithTextStyle(tui.NewStyle().Bold()),
			)
			__tui_9.AddChild(__tui_11)
		} else {
			__tui_12 := tui.New(
				tui.WithText(fmt.Sprintf("%d. %s", i+1, item)),
			)
			__tui_9.AddChild(__tui_12)
		}
	}
	__tui_4.AddChild(__tui_9)
	__tui_13 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1.0),
	)
	__tui_14 := tui.New(
		tui.WithText("Selected (reactive)"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_13.AddChild(__tui_14)
	if len(l.items) == 0 {
		__tui_15 := tui.New(
			tui.WithText("(no items)"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_13.AddChild(__tui_15)
		__tui_16 := tui.New(
			tui.WithText("Index: n/a"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_13.AddChild(__tui_16)
		__tui_17 := tui.New(
			tui.WithText("Length: n/a"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_13.AddChild(__tui_17)
	} else {
		__tui_18 := tui.New(
			tui.WithText(l.selectedItem()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_13.AddChild(__tui_18)
		__tui_19 := tui.New(
			tui.WithText(fmt.Sprintf("Index: %d", l.selectedIndex())),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_13.AddChild(__tui_19)
		__tui_20 := tui.New(
			tui.WithText(fmt.Sprintf("Length: %d chars", len(l.selectedItem()))),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_13.AddChild(__tui_20)
	}
	__tui_4.AddChild(__tui_13)
	__tui_0.AddChild(__tui_4)
	__tui_21 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_22 := tui.New(
		tui.WithText("[j/k] navigate  [q] quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_21.AddChild(__tui_22)
	__tui_0.AddChild(__tui_21)

	return __tui_0
}

func (l *loopsApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*loopsApp)
	if !ok {
		return
	}
	l.items = f.items
}

var _ tui.PropsUpdater = (*loopsApp)(nil)

func (l *loopsApp) BindApp(app *tui.App) {
	if l.selected != nil {
		l.selected.BindApp(app)
	}
}

var _ tui.AppBinder = (*loopsApp)(nil)
