// Code generated by tui generate. DO NOT EDIT.
// Source: feed.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type feedApp struct {
	messages  *tui.State[[]string]
	paused    *tui.State[bool]
	mode      string
	scrollRef *tui.Ref
}

func NewFeedApp(mode string) *feedApp {
	return &feedApp{
		messages:  tui.NewState([]string{}),
		paused:    tui.NewState(false),
		mode:      mode,
		scrollRef: tui.NewRef(),
	}
}

func (f *feedApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.Rune('p'), func(ke tui.KeyEvent) {
			f.paused.Set(!f.paused.Get())
		}),
	}
}

func (f *feedApp) AddMessage(msg string) {
	f.messages.Update(func(msgs []string) []string {
		return append(msgs, msg)
	})
	if el := f.scrollRef.El(); el != nil {
		el.ScrollToBottom()
	}
}

func (f *feedApp) IsPaused() bool {
	return f.paused.Get()
}

func pauseLabel(paused bool) string {
	if paused {
		return "PAUSED"
	}
	return "LIVE"
}

func pauseClass(paused bool) string {
	if paused {
		return "text-yellow font-bold"
	}
	return "text-green font-bold"
}

func lastN(msgs []string, n int) []string {
	if len(msgs) <= n {
		return msgs
	}
	return msgs[len(msgs)-n:]
}

func (f *feedApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_2 := tui.New(
		tui.WithText("Event Loop Demo"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_4 := tui.New(
		tui.WithText("mode:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(f.mode),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_3.AddChild(__tui_5)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithPadding(1),
		tui.WithMinHeight(0),
		tui.WithScrollable(tui.ScrollVertical),
	)
	f.scrollRef.Set(__tui_7)
	for __idx_0, msg := range lastN(f.messages.Get(), 100) {
		_ = __idx_0
		__tui_8 := tui.New(
			tui.WithText(msg),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_7.AddChild(__tui_8)
	}
	__tui_0.AddChild(__tui_7)
	__tui_9 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_11 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_12 := tui.New(
		tui.WithText("p: toggle"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithText("q: quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_13)
	__tui_10.AddChild(__tui_11)
	__tui_14 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_15 := tui.New(
		tui.WithText(pauseLabel(f.paused.Get())),
	)
	__tui_14.AddChild(__tui_15)
	__tui_16 := tui.New(
		tui.WithText(fmt.Sprintf("%d msgs", len(f.messages.Get()))),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_14.AddChild(__tui_16)
	__tui_10.AddChild(__tui_14)
	__tui_0.AddChild(__tui_10)

	return __tui_0
}

func (f *feedApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*feedApp)
	if !ok {
		return
	}
	f.mode = f.mode
}

var _ tui.PropsUpdater = (*feedApp)(nil)

func (f *feedApp) BindApp(app *tui.App) {
	if f.messages != nil {
		f.messages.BindApp(app)
	}
	if f.paused != nil {
		f.paused.BindApp(app)
	}
}

var _ tui.AppBinder = (*feedApp)(nil)
