// Code generated by tui generate. DO NOT EDIT.
// Source: search.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type searchInput struct {
	active *tui.State[bool]
	query  *tui.State[string]
}

func SearchInput(active *tui.State[bool], query *tui.State[string]) *searchInput {
	return &searchInput{active: active, query: query}
}

func (s *searchInput) KeyMap() tui.KeyMap {
	if !s.active.Get() {
		return nil
	}
	return tui.KeyMap{
		tui.OnRunesStop(s.appendChar),
		tui.OnKeyStop(tui.KeyBackspace, s.deleteChar),
		tui.OnKeyStop(tui.KeyEnter, s.submit),
		tui.OnKeyStop(tui.KeyEscape, s.deactivate),
	}
}

func (s *searchInput) appendChar(ke tui.KeyEvent) {
	s.query.Set(s.query.Get() + string(ke.Rune))
}

func (s *searchInput) deleteChar(ke tui.KeyEvent) {
	q := s.query.Get()
	if len(q) > 0 {
		s.query.Set(q[:len(q)-1])
	}
}

func (s *searchInput) submit(ke tui.KeyEvent) {
	s.active.Set(false)
}

func (s *searchInput) deactivate(ke tui.KeyEvent) {
	s.active.Set(false)
	s.query.Set("")
}

func (s *searchInput) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New()
	if s.active.Get() {
		__tui_1 := tui.New(
			tui.WithBorder(tui.BorderRounded),
			tui.WithPadding(1),
		)
		__tui_2 := tui.New(
			tui.WithText("Search:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(s.query.Get()),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_4)
		__tui_0.AddChild(__tui_1)
	}

	return __tui_0
}

func (s *searchInput) BindApp(app *tui.App) {
	if s.active != nil {
		s.active.BindApp(app)
	}
	if s.query != nil {
		s.query.BindApp(app)
	}
}

var _ tui.AppBinder = (*searchInput)(nil)
