package tuigen

import (
	"strings"
	"testing"
)

func TestGenerator_SimpleComponent(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"empty component": {
			input: `package x
templ Empty() {
}`,
			wantContains: []string{
				"type EmptyView struct",
				"Root     *tui.Element",
				"watchers []tui.Watcher",
				"func Empty() EmptyView",
				"var view EmptyView",
				"var watchers []tui.Watcher",
				"return view",
			},
		},
		"component with single element": {
			input: `package x
templ Header() {
	<div></div>
}`,
			wantContains: []string{
				"type HeaderView struct",
				"func Header() HeaderView",
				"__tui_0 := tui.New()",
				"Root:     __tui_0",
			},
		},
		"component with params": {
			input: `package x
templ Greeting(name string, count int) {
	<span>Hello</span>
}`,
			wantContains: []string{
				"func Greeting(name string, count int) GreetingView",
				"type GreetingView struct",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_NestedElements(t *testing.T) {
	input := `package x
templ Layout() {
	<div>
		<div>
			<span>nested</span>
		</div>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Should have 3 element variables
	if !strings.Contains(code, "__tui_0 := tui.New()") {
		t.Error("missing outer box element")
	}

	// Should have AddChild calls
	if !strings.Contains(code, ".AddChild(") {
		t.Error("missing AddChild call")
	}

	// Should return view struct with Root set to outer element
	if !strings.Contains(code, "Root:     __tui_0") {
		t.Error("missing Root assignment to outer element")
	}

	if !strings.Contains(code, "return view") {
		t.Error("missing return view statement")
	}
}

func TestGenerator_TopLevelGoFunc(t *testing.T) {
	input := `package x

func helper(x int) int {
	return x * 2
}

templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "func helper(x int) int") {
		t.Errorf("missing helper function\nGot:\n%s", code)
	}

	if !strings.Contains(code, "return x * 2") {
		t.Errorf("missing helper function body\nGot:\n%s", code)
	}
}

func TestGenerator_ImportPropagation(t *testing.T) {
	input := `package x
import (
	"fmt"
	tui "github.com/grindlemire/go-tui"
)

templ Test() {
	<div direction={tui.Column}>
		<span>{fmt.Sprintf("hello")}</span>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Original imports should be preserved
	if !strings.Contains(code, `"fmt"`) {
		t.Error("missing fmt import")
	}

	if !strings.Contains(code, `"github.com/grindlemire/go-tui"`) {
		t.Error("missing tui root import")
	}
}

func TestGenerator_Header(t *testing.T) {
	input := `package x
templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "Code generated by tui generate. DO NOT EDIT.") {
		t.Error("missing DO NOT EDIT header")
	}

	if !strings.Contains(code, "Source: test.gsx") {
		t.Error("missing source file comment")
	}
}

func TestGenerator_ReactiveIf(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"reactive if with single state var": {
			input: `package x
templ Toggle() {
	count := tui.NewState(0)
	<div>
		@if count.Get() == 0 {
			<span>{"zero"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				"__tui_0.AddChild(__cond_0)",
				"__update___cond_0 := func()",
				"__cond_0.RemoveAllChildren()",
				"if count.Get() == 0",
				"__update___cond_0()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
			},
		},
		"reactive if/else": {
			input: `package x
templ Toggle() {
	count := tui.NewState(0)
	<div>
		@if count.Get() >= 5 {
			<span>{"high"}</span>
		} @else {
			<span>{"low"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				"__update___cond_0 := func()",
				"__cond_0.RemoveAllChildren()",
				"if count.Get() >= 5",
				"} else {",
				"__update___cond_0()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
			},
		},
		"non-reactive if stays plain": {
			input: `package x
templ Static(show bool) {
	<div>
		@if show {
			<span>{"visible"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"if show {",
			},
			wantNotContains: []string{
				"__cond_",
				"RemoveAllChildren",
			},
		},
		"for loop with state in body becomes reactive": {
			input: `package x
templ LoopCond(items []string) {
	count := tui.NewState(0)
	<div>
		@for _, item := range items {
			@if count.Get() > 0 {
				<span>{item}</span>
			}
		}
	</div>
}`,
			wantContains: []string{
				"__loop_0_style := __tui_0.LayoutStyle()",
				"__loop_0 := tui.New(tui.WithDirection(__loop_0_style.Direction), tui.WithGap(__loop_0_style.Gap))",
				"RemoveAllChildren",
				"__update___loop_0 := func()",
				"__update___loop_0()",
				`count.Bind(func(_ int) { __update___loop_0() })`,
			},
			wantNotContains: []string{
				"__cond_", // @if inside @for stays non-reactive
			},
		},
		"for loop without state stays plain": {
			input: `package x
templ PlainLoop(items []string) {
	<div>
		@for _, item := range items {
			<span>{item}</span>
		}
	</div>
}`,
			wantNotContains: []string{
				"__loop_",
				"__cond_",
				"RemoveAllChildren",
			},
		},
		"state in body also triggers binding": {
			input: `package x
import "fmt"
templ Multi() {
	count := tui.NewState(0)
	name := tui.NewState("hello")
	<div>
		@if count.Get() > 0 {
			<span>{fmt.Sprintf("%s: %d", name.Get(), count.Get())}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
				`name.Bind(func(_ string) { __update___cond_0() })`,
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}
