package tuigen

import (
	"strings"
	"testing"
)

func TestGenerator_SimpleComponent(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"empty component": {
			input: `package x
templ Empty() {
}`,
			wantContains: []string{
				"type EmptyView struct",
				"Root     *tui.Element",
				"watchers []tui.Watcher",
				"func Empty() EmptyView",
				"var view EmptyView",
				"var watchers []tui.Watcher",
				"return view",
			},
		},
		"component with single element": {
			input: `package x
templ Header() {
	<div></div>
}`,
			wantContains: []string{
				"type HeaderView struct",
				"func Header() HeaderView",
				"__tui_0 := tui.New()",
				"Root:     __tui_0",
			},
		},
		"component with params": {
			input: `package x
templ Greeting(name string, count int) {
	<span>Hello</span>
}`,
			wantContains: []string{
				"func Greeting(name string, count int) GreetingView",
				"type GreetingView struct",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_NestedElements(t *testing.T) {
	input := `package x
templ Layout() {
	<div>
		<div>
			<span>nested</span>
		</div>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Should have 3 element variables
	if !strings.Contains(code, "__tui_0 := tui.New()") {
		t.Error("missing outer box element")
	}

	// Should have AddChild calls
	if !strings.Contains(code, ".AddChild(") {
		t.Error("missing AddChild call")
	}

	// Should return view struct with Root set to outer element
	if !strings.Contains(code, "Root:     __tui_0") {
		t.Error("missing Root assignment to outer element")
	}

	if !strings.Contains(code, "return view") {
		t.Error("missing return view statement")
	}
}

func TestGenerator_TopLevelGoFunc(t *testing.T) {
	input := `package x

func helper(x int) int {
	return x * 2
}

templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "func helper(x int) int") {
		t.Errorf("missing helper function\nGot:\n%s", code)
	}

	if !strings.Contains(code, "return x * 2") {
		t.Errorf("missing helper function body\nGot:\n%s", code)
	}
}

func TestGenerator_ImportPropagation(t *testing.T) {
	input := `package x
import (
	"fmt"
	tui "github.com/grindlemire/go-tui"
)

templ Test() {
	<div direction={tui.Column}>
		<span>{fmt.Sprintf("hello")}</span>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Original imports should be preserved
	if !strings.Contains(code, `"fmt"`) {
		t.Error("missing fmt import")
	}

	if !strings.Contains(code, `"github.com/grindlemire/go-tui"`) {
		t.Error("missing tui root import")
	}
}

func TestGenerator_Header(t *testing.T) {
	input := `package x
templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "Code generated by tui generate. DO NOT EDIT.") {
		t.Error("missing DO NOT EDIT header")
	}

	if !strings.Contains(code, "Source: test.gsx") {
		t.Error("missing source file comment")
	}
}
