// Code generated by tui generate. DO NOT EDIT.
// Source: streaming.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

func tickElapsed(elapsed *tui.State[int]) func() {
	return func() {
		elapsed.Set(elapsed.Get() + 1)
	}
}

func addLine(lineCount *tui.State[int], content *tui.Element) func(string) {
	return func(line string) {
		lineCount.Set(lineCount.Get() + 1)

		stayAtBottom := content.IsAtBottom()

		lineElem := tui.New(
			tui.WithText(line),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		content.AddChild(lineElem)

		if stayAtBottom {
			content.ScrollToBottom()
		}
	}
}

func handleScrollKeys(content *tui.Element) func(tui.KeyEvent) {
	return func(e tui.KeyEvent) {
		switch e.Rune {
		case 'j':
			content.ScrollBy(0, 1)
		case 'k':
			content.ScrollBy(0, -1)
		}
	}
}

func handleEvent(content *tui.Element) func(tui.Event) bool {
	return func(e tui.Event) bool {
		if mouse, ok := e.(tui.MouseEvent); ok {
			switch mouse.Button {
			case tui.MouseWheelUp:
				content.ScrollBy(0, -1)
				return true
			case tui.MouseWheelDown:
				content.ScrollBy(0, 1)
				return true
			}
		}
		return false
	}
}

type StreamAppView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	Content  *tui.Element
}

func (v StreamAppView) GetRoot() tui.Renderable { return v.Root }

func (v StreamAppView) GetWatchers() []tui.Watcher { return v.watchers }

func StreamApp(dataCh <-chan string) StreamAppView {
	var view StreamAppView
	var watchers []tui.Watcher

	var Content *tui.Element

	lineCount := tui.NewState(0)
	elapsed := tui.NewState(0)
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
	)
	__tui_1 := tui.New(
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("Streaming DSL Demo - Use j/k to scroll, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	Content = tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithFocusable(true),
	)
	__tui_0.AddChild(Content)
	__tui_3 := tui.New(
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_4 := tui.New(
		tui.WithText(fmt.Sprintf("Lines: %d | Elapsed: %ds | Press q to exit", lineCount.Get(), elapsed.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_3.AddChild(__tui_4)
	__tui_0.AddChild(__tui_3)

	// Attach handlers (deferred until refs are assigned)
	Content.SetOnKeyPress(handleScrollKeys(Content))
	Content.SetOnEvent(handleEvent(Content))

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, tickElapsed(elapsed)))
	__tui_0.AddWatcher(tui.Watch(dataCh, addLine(lineCount, Content)))

	// State bindings
	__update___tui_4 := func() {
		__tui_4.SetText(fmt.Sprintf("Lines: %d | Elapsed: %ds | Press q to exit", lineCount.Get(), elapsed.Get()))
	}
	lineCount.Bind(func(_ int) { __update___tui_4() })
	elapsed.Bind(func(_ int) { __update___tui_4() })

	view = StreamAppView{
		Root:     __tui_0,
		watchers: watchers,
		Content:  Content,
	}
	return view
}
