// Code generated by tui generate. DO NOT EDIT.
// Source: streaming.tui

package main

import (
	"fmt"
	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

type HeaderView struct {
	Root *element.Element
}

func Header() HeaderView {
	var view HeaderView

	__tui_0 := element.New(
		element.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		element.WithBorder(tui.BorderSingle),
		element.WithHeight(3),
		element.WithDirection(layout.Row),
		element.WithJustify(layout.JustifyCenter),
		element.WithAlign(layout.AlignCenter),
	)
	__tui_1 := element.New(
		element.WithText("Streaming DSL Demo - Use j/k, PgUp/PgDn, Arrow Keys to scroll"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_0.AddChild(__tui_1)

	view = HeaderView{
		Root: __tui_0,
	}
	return view
}

type FooterView struct {
	Root *element.Element
}

func Footer(scrollY int, maxScroll int, autoScrollStatus string) FooterView {
	var view FooterView

	__tui_0 := element.New(
		element.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		element.WithBorder(tui.BorderSingle),
		element.WithHeight(3),
		element.WithDirection(layout.Row),
		element.WithJustify(layout.JustifyCenter),
		element.WithAlign(layout.AlignCenter),
	)
	__tui_1 := element.New(
		element.WithText(fmt.Sprintf("Scroll: %d/%d | Auto-scroll: %s | Press ESC to exit", scrollY, maxScroll, autoScrollStatus)),
		element.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_0.AddChild(__tui_1)

	view = FooterView{
		Root: __tui_0,
	}
	return view
}
