// Code generated by tui generate. DO NOT EDIT.
// Source: hello.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type HelloView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v HelloView) GetRoot() tui.Renderable { return v.Root }

func (v HelloView) GetWatchers() []tui.Watcher { return v.watchers }

func Hello() HelloView {
	var view HelloView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithHeightPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithText("Hello, TUI!"),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	view = HelloView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
