// Code generated by tui generate. DO NOT EDIT.
// Source: scrollable.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type scrollableApp struct {
	items   []string
	scrollY *tui.State[int]
	content *tui.Ref
}

func Scrollable(items []string) *scrollableApp {
	return &scrollableApp{
		items:   items,
		scrollY: tui.NewState(0),
		content: tui.NewRef(),
	}
}

func (s *scrollableApp) scrollBy(delta int) {
	el := s.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := s.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	s.scrollY.Set(newY)
}

func (s *scrollableApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { s.scrollBy(1) }),
		tui.OnRune('k', func(ke tui.KeyEvent) { s.scrollBy(-1) }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { s.scrollBy(1) }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { s.scrollBy(-1) }),
	}
}

func (s *scrollableApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		s.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		s.scrollBy(1)
		return true
	}
	return false
}

func (s *scrollableApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
	)
	__tui_1 := tui.New(
		tui.WithText("Scrollable Content"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, s.scrollY.Get()),
	)
	s.content.Set(__tui_3)
	for i, item := range s.items {
		_ = i
		__tui_4 := tui.New(
			tui.WithText(fmt.Sprintf("%02d. %s", i+1, item)),
		)
		__tui_3.AddChild(__tui_4)
	}
	__tui_0.AddChild(__tui_3)
	__tui_5 := tui.New(
		tui.WithText("j/k or arrow keys to scroll, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_5)

	return __tui_0
}

func (s *scrollableApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*scrollableApp)
	if !ok {
		return
	}
	s.items = f.items
}

var _ tui.PropsUpdater = (*scrollableApp)(nil)

func (s *scrollableApp) BindApp(app *tui.App) {
	if s.scrollY != nil {
		s.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*scrollableApp)(nil)
