// Code generated by tui generate. DO NOT EDIT.
// Source: panes.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type panes struct {
	active  int
	content []*tui.Element
	items   []*tui.Element
	footer  *tui.Element
}

func NewPanes(active int) *panes {
	return &panes{
		active: active,
		content: []*tui.Element{
			tui.New(tui.WithText("Pane A")),
			tui.New(tui.WithText("Pane B")),
		},
		items: []*tui.Element{
			tui.New(tui.WithText("item 1")),
			tui.New(tui.WithText("item 2")),
		},
		footer: tui.New(tui.WithText("footer")),
	}
}

func (p *panes) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
	)
	__tui_1 := p.content[p.active].Render(app)
	__tui_0.AddChild(__tui_1)
	for __idx_0, el := range p.items {
		_ = __idx_0
		__tui_2 := el.Render(app)
		__tui_0.AddChild(__tui_2)
	}
	__tui_3 := p.footer.Render(app)
	__tui_0.AddChild(__tui_3)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (p *panes) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*panes)
	if !ok {
		return
	}
	p.active = f.active
	p.content = f.content
	p.items = f.items
	p.footer = f.footer
}

func (p *panes) UpdateProps(fresh tui.Component) {
	p.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*panes)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (p *panes) bindAppFields(app *tui.App) {
	if binder, ok := any(p.footer).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
}

func (p *panes) BindApp(app *tui.App) {
	p.bindAppFields(app)
}

var _ tui.AppBinder = (*panes)(nil)

// unbindAppFields is generated. It detaches topic-based Events
// subscriptions and any component-expression AppUnbinder fields.
// Call this from your UnbindApp if you override it.
func (p *panes) unbindAppFields() {
	if unbinder, ok := any(p.footer).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
}

func (p *panes) UnbindApp() {
	p.unbindAppFields()
}

var _ tui.AppUnbinder = (*panes)(nil)
