// Code generated by tui generate. DO NOT EDIT.
// Source: crosspkg.gsx

package testdata

import (
	"example.com/external/widgets"
	tui "github.com/grindlemire/go-tui"
)

type CrossPackageView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *CrossPackageView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *CrossPackageView) GetRoot() *tui.Element { return v.Root }

func (v *CrossPackageView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *CrossPackageView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *CrossPackageView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *CrossPackageView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*CrossPackageView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*CrossPackageView)(nil)

var _ tui.AppUnbinder = (*CrossPackageView)(nil)

var _ tui.PropsUpdater = (*CrossPackageView)(nil)

func CrossPackage(title string) *CrossPackageView {
	var view CrossPackageView
	var watchers []tui.Watcher

	__tui_0 := tui.New()
	__tui_1 := widgets.Header(title)
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = CrossPackageView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
