// Code generated by tui generate. DO NOT EDIT.
// Source: elementexpr.gsx

package testdata

import (
	tui "github.com/grindlemire/go-tui"
)

type tabs struct {
	active  int
	content []*tui.Element
	items   []*tui.Element
	footer  *tui.Element
}

func Tabs(active int, content []*tui.Element) *tabs {
	return &tabs{active: active, content: content}
}

func (t *tabs) Render(app *tui.App) *tui.Element {
	current := t.content[t.active].Render(app)
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
	)
	__tui_0.AddChild(current)
	for __idx_0, el := range t.items {
		_ = __idx_0
		__tui_1 := el.Render(app)
		__tui_0.AddChild(__tui_1)
	}
	if t.footer != nil {
		__tui_2 := t.footer.Render(app)
		__tui_0.AddChild(__tui_2)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (t *tabs) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*tabs)
	if !ok {
		return
	}
	t.active = f.active
	t.content = f.content
	t.items = f.items
	t.footer = f.footer
}

func (t *tabs) UpdateProps(fresh tui.Component) {
	t.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*tabs)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (t *tabs) bindAppFields(app *tui.App) {
	if binder, ok := any(t.footer).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	for _, item := range t.content {
		if binder, ok := any(item).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}
	for _, item := range t.items {
		if binder, ok := any(item).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}
}

func (t *tabs) BindApp(app *tui.App) {
	t.bindAppFields(app)
}

var _ tui.AppBinder = (*tabs)(nil)

// unbindAppFields is generated. It detaches topic-based Events
// subscriptions and any component-expression AppUnbinder fields.
// Call this from your UnbindApp if you override it.
func (t *tabs) unbindAppFields() {
	if unbinder, ok := any(t.footer).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	for _, item := range t.content {
		if unbinder, ok := any(item).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}
	for _, item := range t.items {
		if unbinder, ok := any(item).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}
}

func (t *tabs) UnbindApp() {
	t.unbindAppFields()
}

var _ tui.AppUnbinder = (*tabs)(nil)
