// Code generated by tui generate. DO NOT EDIT.
// Source: markdown.gsx

package testdata

import (
	tui "github.com/grindlemire/go-tui"
)

type docView struct {
	readme string
}

func DocView(readme string) *docView {
	return &docView{readme: readme}
}

func (c *docView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithScrollable(tui.ScrollVertical),
	)
	__tui_1 := app.MountPersistent(c, 0, func() tui.Component {
		return tui.NewMarkdown(
			tui.WithMarkdownSource(c.readme),
			tui.WithMarkdownWidth(80),
		)
	})
	__tui_0.AddChild(__tui_1)

	return __tui_0
}

func (c *docView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*docView)
	if !ok {
		return
	}
	c.readme = f.readme
}

var _ tui.PropsUpdater = (*docView)(nil)
