// Code generated by tui generate. DO NOT EDIT.
// Source: other.gsx

package testdata

import (
	tui "github.com/grindlemire/go-tui"
)

func otherHelperFunction(s string) string {
	return fmt.Sprintf("[%s]", s)
}
