// Code generated by tui generate. DO NOT EDIT.
// Source: other.tui

package testdata

import (
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func otherHelperFunction(s string) string {
	return fmt.Sprintf("[%s]", s)
}
