// Code generated by tui generate. DO NOT EDIT.
// Source: simple.gsx

package testdata

import (
	tui "github.com/grindlemire/go-tui"
)

func Header(title string) *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
	)
	__tui_0.AddChild(__tui_1)
	return __tui_0
}

func Footer() *tui.Element {
	__tui_0 := tui.New(
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Footer content"),
	)
	__tui_0.AddChild(__tui_1)
	return __tui_0
}
